### ISSUE TITLE
not related to a problem, can you help solving a problem in a custome node for ComfyUI?

### ISSUE THREAD

**Issue by YarvixPA** [spacepxl/ComfyUI-StyleGan#2]
Hello, I would like to know how I could contact you so that you can help me with a node that I am creating.

It is inspired by comfyui-inpaint-nodes (I have seen that you have collaborated there) but I am having difficulties regarding the results

For some reason in the node image output as a result it gives me 3 results with the fill method (navier-stokes) and not with the correct image color

I'm not trying to copy your extension, rather I'm trying to have a node that provides inpainting functions like in automatic1111
I would appreciate it if you could give me a hand with this project and provide me with some way to contact you.

![2a596fa9-fae9-42aa-954d-da7c02e4307b](https://github.com/spacepxl/ComfyUI-StyleGan/assets/152553832/1bf9a7b6-af0a-42ee-9892-ebc190d0181e)
![fb053996-4417-4879-bd10-e2d6ae8ccb38](https://github.com/spacepxl/ComfyUI-StyleGan/assets/152553832/8d46951a-155c-454b-b030-32c7dc9b1fb4)

**Comment by spacepxl** [comment]
Looks like you have your image tensor out of order, and the 3 channels are being interpreted as 3 separate grayscale images. Without seeing the code it's hard to know exactly where, but Comfy uses [B,H,W,C] order for image tensors, and OpenCV usually wants [H,W,C] numpy arrays. So for example, the shape of the image tensor in and out of your node could be something like [1, 1024, 1024, 3].

**Comment by YarvixPA** [comment]
Can you share your email or your name on Discord with me so I can upload the files?

**Comment by spacepxl** [comment]
sure, discord: ...

**Comment by YarvixPA** [comment]
Ready, I already wrote you in discord
